## Softmax Function
In both softmax regression and neural networks with Softmax outputs, N outputs are generated and one output is selected as the predicted category. In both cases a vector  𝐳
  is generated by a linear function which is applied to a softmax function. The softmax function converts  𝐳
  into a probability distribution as described below. After applying softmax, each output will be between 0 and 1 and the outputs will add to 1, so that they can be interpreted as probabilities. The larger inputs will correspond to larger output probabilities.

The loss function associated with Softmax, the cross-entropy loss, is:
\begin{equation}
  L(\mathbf{a},y)=\begin{cases}
    -log(a_1), & \text{if $y=1$}.\\
        &\vdots\\
     -log(a_N), & \text{if $y=N$}
  \end{cases}
\end{equation}

Where y is the target category for this example and $\mathbf{a}$ is the output of a softmax function. In particular, the values in $\mathbf{a}$ are probabilities that sum to one.

In [17]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from sklearn.datasets import make_blobs
import logging
logging.getLogger("tensorflow").setLevel(logging.ERROR)
tf.autograph.set_verbosity(0)

In [18]:
# making  dataset for example
centers = [[-5, 2], [-2, -2], [1, 2], [5, -2]]
X_train, y_train = make_blobs(n_samples=2000, centers=centers, cluster_std=1.0,random_state=30)
X_train,y_train


(array([[ 1.55508243,  0.84801682],
        [-5.33749882,  1.03397255],
        [-4.09353183,  0.67843096],
        ...,
        [-0.84437575, -1.94991543],
        [ 5.0377068 , -2.92221685],
        [ 0.38198674,  1.49735733]]),
 array([2, 0, 0, ..., 1, 3, 2]))

TensorFlow

In [19]:
model = Sequential(
    [
        Dense(25, activation = 'relu'),
        Dense(15, activation = 'relu'),
        Dense(4, activation = 'softmax')
    ]
)
model.compile(loss=tf.keras.losses.SparseCategoricalCrossentropy())

model.fit(X_train,y_train,epochs=10)


Epoch 1/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 1.1971
Epoch 2/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4748  
Epoch 3/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.1809
Epoch 4/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0723
Epoch 5/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0519
Epoch 6/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0478  
Epoch 7/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0355  
Epoch 8/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0364  
Epoch 9/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0349  
Epoch 10/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0319  


#### More stable and accurate results can be obtained if the softmax and loss are combined during training. {from_logits = True}. This informs the loss function that the softmax operation should be included in the loss calculation. This allows for an optimized implementation.

In [20]:
preferred_model = Sequential(
    [
        Dense(25, activation = 'relu'),
        Dense(15, activation = 'relu'),
        Dense(4, activation = 'linear')
    ]
)
preferred_model.compile(loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True))
preferred_model.fit(X_train,y_train,epochs=10)

Epoch 1/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - loss: 1.4232  
Epoch 2/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.4229  
Epoch 3/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 0.1555
Epoch 4/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0683  
Epoch 5/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0511
Epoch 6/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0414
Epoch 7/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0443  
Epoch 8/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0361  
Epoch 9/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 0.0319
Epoch 10/10
63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step - loss: 0.0300  


In [21]:
p_preferred = preferred_model.predict(X_train)
print(f"two example output vectors:\n {p_preferred[:2]}")


63/63 ━━━━━━━━━━━━━━━━━━━━ 0s 1ms/step  
two example output vectors:
 [[-3.7370126  -2.077444    6.5579786   0.87716806]
 [ 9.925746    3.1870847  -0.5626399  -5.90301   ]]


### the outputs are not probabilities, but can range from large negative numbers to large positive numbers. The output must be sent through a softmax when performing a prediction that expects a probability.

In [22]:
sm_preferred = tf.nn.softmax(p_preferred).numpy()
print(f"two example output vectors:\n {sm_preferred[:2]}")


two example output vectors:
 [[3.3679971e-05 1.7705707e-04 9.9639076e-01 3.3984827e-03]
 [9.9878919e-01 1.1827976e-03 2.7824388e-05 1.3339279e-07]]


### We can find the index of the largest value by np.argmax()

In [24]:
for i in range(5):    # as the total units in 3rd layer = 4
    print( f"{p_preferred[i]}\t -Category: {np.argmax(p_preferred[i])}")

[-3.7370126  -2.077444    6.5579786   0.87716806]	 -Category: 2
[ 9.925746   3.1870847 -0.5626399 -5.90301  ]	 -Category: 0
[ 7.227459    3.0024202  -0.53485864 -4.9019804 ]	 -Category: 0
[-1.1252525  5.380452  -1.458927  -2.5653954]	 -Category: 1
[ 0.63214886 -1.8742423   8.596048   -2.9868457 ]	 -Category: 2
